### ISSUE TITLE
Not working on iPhone 6s 13.3

### ISSUE THREAD

**Issue by CobreDev** [mealdy/nfcunblock#1]
In the Shortcuts app on my 13.3 iPhone 6s, the NFC trigger shows in the automation settings, but when I try to scan the tag I want to use, nothing happens. On a stock XR (Where NFC Shortcuts are natively supported), a little window pops up and I can scan my tag

**Comment by DocSystem** [comment]
Same issue on iPhone SE 13.2.2

**Comment by mealdy** [comment]
If background reading doesn't work, try to run `killall -9 nfcd;` in ssh or terminal window.

**Comment by DocSystem** [comment]
I tried but it but it didn’t change anything... the popup doesn’t show up!

**Comment by mealdy** [comment]
If that doesn't work, this would be probably a limit by the device, so no way to fix it. I will close this issue.
